- name: copy file4 to slaves
  template:
    src: 4.sql.j2
    dest: "{{ volume }}4.sql"

- name: run 4.sql on con
  shell: docker exec mssql /opt/mssql-tools/bin/sqlcmd -U sa -S {{ inventory_hostname }},{{ port }} -P {{ password }} -i /var/opt/mssql/4.sql
