- name: copy file5 to master
  template:
    src: 5.sql.j2
    dest: "{{ volume }}5.sql"

- name: run 5.sql on con
  shell: docker exec mssql /opt/mssql-tools/bin/sqlcmd -U sa -S {{ inventory_hostname }},{{ port }} -P {{ password }} -i /var/opt/mssql/5.sql
