- name: copy file3 to master
  template:
    src: 3.sql.j2
    dest: "{{ volume }}3.sql"

- name: run 3.sql on master
  shell: docker exec mssql /opt/mssql-tools/bin/sqlcmd -U sa -S {{ inventory_hostname }},{{ port }} -P {{ password }} -i /var/opt/mssql/3.sql
